# services:
#   nginx:
#     build: ./nginx
#     container_name: nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       # 외부 인증서 및 시스템 파일
#       - /etc/letsencrypt:/etc/letsencrypt:ro
#       - /etc/ssl/certs:/etc/ssl/certs:ro
#       # 런타임에 변경 가능한 파일들만 볼륨 마운트
#       - ./nginx/conf.d:/etc/nginx/conf.d:rw
#       - ./nginx/logs:/var/log/nginx
#     networks:
#       - undaied
#     restart: always

# networks:
#   undaied:
#     external: true